# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Brown\UsuarioBundle\Entity\Usuario:
            algorithm: bcrypt

    providers:
        usuarios:
            entity:
                class: Brown\UsuarioBundle\Entity\Usuario
                property: dni

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: usuarios
            form_login:
                login_path: /login
                check_path: /login_check
                #failure_handler: brown.usuarios.login.failure
            logout:
                path: /logout
                target: /
            switch_user: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/olvide-mi-contrasena, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar-contrasena, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetear-contrasena/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirmar*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/*, roles: ROLE_USER }

    role_hierarchy:
        ROLE_EMPLEADO: ROLE_USER
        ROLE_ADMIN: ROLE_EMPLEADO

