<?php
/**
 * Created by PhpStorm.
 * User: Agustín Houlgrave
 * Date: 07/09/2015
 * Time: 12:25 PM
 */

namespace Brown\ServicioBundle\Form;


use Symfony\Component\Form\FormBuilderInterface;

class EditarServicioType extends NuevoServicioType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->remove('submit');
        $builder->add('submit','submit', array(
            'label' => 'Guardar cambios',
            'attr' => array('class' => 'btn-primary')
        ));
    }


}